### ISSUE TITLE
MouseUnSnagTests build is broken

### ISSUE THREAD

**Issue by GrantMoyer** [MouseUnSnag/MouseUnSnag#1]
MouseUnSnagTests.csproj build is broken, which prevents MouseUnSnag.sln from building. MouseUnSnag.csproj still builds though.

**Comment by GrantMoyer** [comment]
This may just be a problem in a mono environment.

**Comment by patricknelson** [comment]
Once fixed, will this automatically incorporate the tagged builds into the releases page?

**Comment by patricknelson** [comment]
p.s. I'd love to try and tackle but I'm only vaguely familiar with C# and most of my dev experience (especially CI/CD stuff) is in the realm of Linux based environments.

**Comment by GrantMoyer** [comment]
This is partly addressed #15, since it replaces Visual Studio's unit tests framework with the cross platform NUnit. However, some of the tests still don't run successfully on Linux, since they depend on Windows DLLs. Although the software is only intended to be run on Windows, it would be nice to be able to run the full test suite from a Linux development environment.

**Comment by GrantMoyer** [comment]
Fixed by #18.
