### ISSUE TITLE
Test on Windows 11

### ISSUE THREAD

**Issue by patricknelson** [MouseUnSnag/MouseUnSnag#10]
We should have someone who already has an installation of Windows 11 test this application to verify that it is still working as expected.

**Comment by DovieW** [comment]
I just tried on Win 11, and it seems to work fine. Man, this program is awesome!

**Comment by bsak-shell** [comment]
Works on my Win11 as well, so we can assume the tests passed 😄

**Comment by patricknelson** [comment]
Alright, thanks for testing folks. Closing this out.
