### ISSUE TITLE
Auto-start with "Unstick from corners" only

### ISSUE THREAD

**Issue by dookei** [MouseUnSnag/MouseUnSnag#14]
Hi there, 
thank you very much for this application. I use 4 monitors and I was getting exhausted with the sticky corners when moving between monitors.
I just have a quick feature request. is it possible to auto-start with just "Unstick from corners".
![image](https://user-images.githubusercontent.com/24986481/153882839-7dec48d6-f223-4adc-9f10-f6349e52d9e8.png)

Many thanks.

**Comment by patricknelson** [comment]
Hi @dookei, glad you're enjoying it! This is actually already implemented but not yet released (and also needs to be documented, see #11 for that). Basically the feature is the retention of the settings (i.e. those checked options) on next app start.

I do have an unofficial build on my own fork that merges in the latest code and includes pull requests that I have waiting to be merged here if you'd like to run with that for now until a new official version is released (probably v2.2). https://github.com/patricknelson/MouseUnSnag/releases

**Comment by patricknelson** [comment]
Ok v2.2 is now released! 😊  You can check it out here: https://github.com/MouseUnSnag/MouseUnSnag/releases
