### ISSUE TITLE
"Jump between monitors" permanently enabled, no way to turn it off

### ISSUE THREAD

**Issue by mdmitry** [MouseUnSnag/MouseUnSnag#22]
I've tried MouseUnSnag only to fix mouse getting stuck in the corners. While "UnStick from corners" and "Wrap around monitors" functions work as expected and can be turned on/off, the "Jump between monitors" function is now active all the time, whether it's checked or not, even if the program is not running, even after the reboot (MouseUnSnag is not in startup).

My arrangement is like this:
![monitor_cfg](https://user-images.githubusercontent.com/683650/201461384-ca694dad-b229-4c75-b5c0-a065fef1c628.png)

I really want mouse NOT to teleport upwards to screen 2 when I touch the right edge of monitor 1 with the cursor, and it is now impossible.

Please help me troubleshoot this one, instead of making multi-monitor experience better, MouseUnSnag made it much worse.

Running Windows 11, and I don't have admin rights on this PC, and I can't test the Safe Mode because of BitLocker enabled.

**Comment by mdmitry** [comment]
It was "Ease cursor movement between displays" checkbox in Settings > System > Display.
And it behaves differently than MouseUnSnag.
![jump](https://user-images.githubusercontent.com/683650/201588975-b8248722-dbc9-4569-9757-6256cb516706.png)

**Comment by patricknelson** [comment]
Yeesh... the way Win11 does it seems unintuitive. Odd that it ends up midway down the next monitor over instead of as close as possible to the last position. Glad you figured it out and sorry for the late response, @mdmitry!
