### ISSUE TITLE
Google Chrome causes sticky corners to return

### ISSUE THREAD

**Issue by BrianMikkilaSoftware** [MouseUnSnag/MouseUnSnag#25]
First, I just wanted to say thank you to the authors of this project. 

I've encountered an issue when running MouseUnSnag V2.2 on a Windows 11 system. Whenever a Chrome window is open and visible, the sticky corners behavior returns. The sticky corners go away if Chrome is minimized to the taskbar or closed. I've tried about a dozen other programs and none of them cause the same behavior. This happened using the latest version of Chrome as of this post (117.0.5938.92) and no extensions. 

Has anyone else seen this behavior? If so, is there a known workaround?

**Comment by patricknelson** [comment]
Not 100% sure, but: Is it possible that Chrome is running with higher privileges, maybe? I’ve seen issues like that with other software that I use where when Windows is focused on an app running under a different user (or with elevated permissions), other apps cannot interact with it (e.g. AltDrag running with regular privileges attempting to move the task manager which always runs with elevated privs).

To test this, try closing MouseUnSnag and then running it by right clicking and running it with administrator privileges. If it works then, it’s an issue with maybe Chrome running with higher permissions, maybe.

**Comment by BrianMikkilaSoftware** [comment]
Running MouseUnSnag as administrator fixes it. I appreciate the solution and the rapid response. Hopefully this helps someone else in the future.

**Comment by patricknelson** [comment]
No problem. Alternatively, you might also consider running Chrome with reduced privileges. Particularly for security reasons. As a web developer with a bit of a security background, I can certainly say that's a risky proposition (of course that is tempered with your needs, assuming there's a good reason for it of course). Good luck!
