### ISSUE TITLE
Suggestion: Include in Microsoft PowerToys

### ISSUE THREAD

**Issue by mrandreastoth** [MouseUnSnag/MouseUnSnag#32]
This is such a much needed utility for Windows. It really should be a Windows feature, but the next best thing would be to clean it up and try to have it included in Microsoft PowerToys.

**Comment by patricknelson** [comment]
This is not something we have any control over at all. I think if you'd like the functionality offered by Mouse UnSnag included into Microsoft's PowerToys utilities, you'd have to ask Microsoft to include that on their end. 😅
